version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1000M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=9200
        - traefik.frontend.rule=Host:elasticsearch.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/limits.conf:/etc/security/limits.conf
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.3
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
            TZ: Europe/Paris
            LOGSPOUT: ignore
    volumes:
            - ./logstash/conf:/conf
    command: logstash -f /conf/gelf.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.15"
          memory: 150M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=5601
        - traefik.frontend.rule=Host:kibana.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    environment:
        - ELASTICSEARCH_PASSWORD = changeme
    volumes:
        - ./kibana/kibana.yml:/etc/kibana/kibana.yml

#  logspout:
#    build: logspout
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 50M
#      restart_policy:
#        condition: on-failure
#    volumes:
#            - /var/run/docker.sock:/tmp/docker.sock
#    command: logstash://morpheus.alin.be:5000 

networks:
  default:
    external:
      name: traefik-net
